# Conexion a PostgreSQL (Aiven)
spring.datasource.url=jdbc:postgresql://postgres-bus-db-proyecto-bus.e.aivencloud.com:27020/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Tuk2AzTd_LyXFV5M70E
spring.datasource.driver-class-name=org.postgresql.Driver
